import { useState } from "react";
import { FileText, Loader2 } from "lucide-react";

export default function NoteForm({ onSubmit, onCancel }) {
  const [form, setForm] = useState({ title: "", content: "", tags: "" });
  const [loading, setLoading] = useState(false);

  const update = (field) => (e) =>
    setForm((prev) => ({ ...prev, [field]: e.target.value }));

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!form.title.trim() || !form.content.trim()) return;

    setLoading(true);
    try {
      const tags = form.tags
        .split(",")
        .map((t) => t.trim())
        .filter(Boolean);

      await onSubmit({
        title: form.title.trim(),
        content: form.content.trim(),
        tags,
      });
      setForm({ title: "", content: "", tags: "" });
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="bg-white border border-gray-200 rounded-2xl p-6 shadow-sm">
      <h3 className="text-lg font-bold text-gray-900 mb-5 flex items-center gap-2">
        <FileText size={20} className="text-blue-500" />
        New Note
      </h3>

      <form onSubmit={handleSubmit} className="space-y-4">
        {/* Title */}
        <div>
          <label className="block text-sm font-bold text-gray-700 mb-1.5 uppercase tracking-wider text-xs">Title</label>
          <input
            type="text"
            value={form.title}
            onChange={update("title")}
            placeholder="Note title"
            required
            className="w-full bg-white border border-gray-300 rounded-xl px-4 py-2.5 text-gray-900 placeholder-gray-400 focus:outline-none focus:border-blue-500 focus:ring-1 focus:ring-blue-500 transition-all duration-200 text-sm"
          />
        </div>

        {/* Content */}
        <div>
          <label className="block text-sm font-bold text-gray-700 mb-1.5 uppercase tracking-wider text-xs">Content</label>
          <textarea
            value={form.content}
            onChange={update("content")}
            placeholder="Write your note here…"
            rows={4}
            required
            className="w-full bg-white border border-gray-300 rounded-xl px-4 py-2.5 text-gray-900 placeholder-gray-400 focus:outline-none focus:border-blue-500 focus:ring-1 focus:ring-blue-500 transition-all duration-200 text-sm resize-y min-h-[100px]"
          />
        </div>

        {/* Tags */}
        <div>
          <label className="block text-sm font-bold text-gray-700 mb-1.5 uppercase tracking-wider text-xs">Tags</label>
          <input
            type="text"
            value={form.tags}
            onChange={update("tags")}
            placeholder="e.g. math, calculus, midterm"
            className="w-full bg-white border border-gray-300 rounded-xl px-4 py-2.5 text-gray-900 placeholder-gray-400 focus:outline-none focus:border-blue-500 focus:ring-1 focus:ring-blue-500 transition-all duration-200 text-sm"
          />
          <p className="text-gray-500 text-xs mt-1.5">
            Separate tags with commas. Tags will also be auto-generated by AI.
          </p>
        </div>

        {/* Actions */}
        <div className="flex items-center gap-3 pt-2">
          <button
            type="submit"
            disabled={loading}
            className="flex-1 py-2.5 rounded-xl font-bold text-sm text-white bg-blue-600 hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed transition-all duration-200 cursor-pointer flex items-center justify-center gap-2 shadow-sm"
          >
            {loading ? (
              <>
                <Loader2 size={16} className="animate-spin" /> Saving…
              </>
            ) : (
              "Save Note"
            )}
          </button>
          <button
            type="button"
            onClick={onCancel}
            className="px-5 py-2.5 rounded-xl text-sm font-bold text-gray-600 bg-white border border-gray-200 hover:bg-gray-50 transition-all duration-200 cursor-pointer shadow-sm"
          >
            Cancel
          </button>
        </div>
      </form>
    </div>
  );
}
